name: Test


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel all builds
        uses: styfle/cancel-workflow-action
        with:
          access_token: ${{  github.token  }}


  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Intalling Dependencies of Project
        run: npm ci
      - name: Testing with Jest
        run: npm run test

  # build:
  #   needs: [eslint]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: Intalling Dependencies of Project
  #       run: npm ci
  #     - name: Building Application
  #       run: npm run build
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: dist
  #         path: dist
